apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-latest
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: laimage=https://crmasraf001.azurecr.io/enhanced-devops
    argocd-image-updater.argoproj.io/laimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git       
    argocd-image-updater.argoproj.io/git-branch: prod      
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/laimage.force-update: "true"
spec:
  project: default
  source: 
    repoURL: https://github.com/xokacar/auto-latest
    path: ./auto-latest-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy: 
      automated:
        prune: true
        selfHeal: true
