replicaCount: 3  

frontend:
  name: backend
image:
    name: crmasraf001.azurecr.io/enhanced-devops
    tag: latest
    repository: crmasraf001.azurecr.io/enhanced-devops
    pullPolicy: Always

imagePullSecrets:
  - name: acr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "auto-latest-service"

service:
  type: ClusterIP
  port: 80

# Other values can remain as-is or adjust as needed.
